In [1]:
import pandas as pd
import pandas_profiling
from pandas_profiling.profile_report import ProfileReport

In [5]:
data = pd.read_csv('../pandas_profiling/globalterrorismdb_0718dist.csv', low_memory=False)

In [6]:
data.head(3)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [ ]:
prof = data.profile_report(title='Pandas Profiling Report', progress_bar=False)
prof